export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_GO_BACK = "AUTH_GO_BACK";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const LIST_ENTRIES_REQUEST = "LIST_ENTRIES_REQUEST";
export const LIST_ENTRIES_SUCCESS = "LIST_ENTRIES_SUCCESS";
export const LIST_ENTRIES_FAIL = "LIST_ENTRIES_FAIL";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAIL = "USER_SEARCH_FAIL";
export const USER_SEARCH_RESET = "USER_SEARCH_RESET";

export const LIST_SEARCH_REQUEST = "LIST_SEARCH_REQUEST";
export const LIST_SEARCH_SUCCESS = "LIST_SEARCH_SUCCESS";
export const LIST_SEARCH_FAIL = "LIST_SEARCH_FAIL";
export const LIST_SEARCH_RESET = "LIST_SEARCH_RESET";

export const LIST_SHOW = "LIST_SHOW";
export const LIST_SHOW_EDIT = "LIST_SHOW_EDIT";
export const LIST_CREATE_REQUEST = "LIST_CREATE_REQUEST";
export const LIST_CREATE_SUCCESS = "LIST_CREATE_SUCCESS";
export const LIST_RESET = "LIST_RESET";

export const EDIT_LIST_REQUEST = "EDIT_LIST_REQUEST";
export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS";
export const EDIT_LIST_FAIL = "EDIT_LIST_FAIL";

export const STORE_MESSAGES = "STORE_MESSAGES";
export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";

export const STORE_FOLLOW_DATA = "STORE_FOLLOW_DATA";
export const NEW_FOLLOWER = "NEW_FOLLOWER";
export const NEW_FOLLOWING = "NEW_FOLLOWING";
