export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_GO_BACK = "AUTH_GO_BACK";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const LIST_ENTRIES_REQUEST = "LIST_ENTRIES_REQUEST";
export const LIST_ENTRIES_SUCCESS = "LIST_ENTRIES_SUCCESS";
export const LIST_ENTRIES_FAIL = "LIST_ENTRIES_FAIL";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAIL = "USER_SEARCH_FAIL";
export const USER_SEARCH_RESET = "USER_SEARCH_RESET";

export const LIST_SEARCH_REQUEST = "LIST_SEARCH_REQUEST";
export const LIST_SEARCH_SUCCESS = "LIST_SEARCH_SUCCESS";
export const LIST_SEARCH_FAIL = "LIST_SEARCH_FAIL";
export const LIST_SEARCH_RESET = "LIST_SEARCH_RESET";
